language: rust
rust:
  - stable
  - beta
  - nightly

branches:
  except:
    - dev

script:
  - cargo build --verbose --all
  - cargo test  --verbose --all
  - bash tests/dev_test.sh

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
