[package]
name = "rsbx"
version = "0.1.0"
authors = ["Darren Ldl <darrenldldev@gmail.com>"]

[dependencies]
crcccitt     = { path = "crcccitt" }
reed-solomon-erasure = { path = "reed-solomon-erasure" }
ring         = "0.12.1"
blake        = "2.0.0"
hex-slice    = "0.1.2"
rand = "0.3"