[package]
name = "rsbx"
version = "0.9.0"
authors = ["Darren Ldl <darrenldldev@gmail.com>"]

[dependencies]
crc-ccitt            = { path = "crc-ccitt" }
reed-solomon-erasure = "3.0"
ring                 = "0.12.1"
hex-slice            = "0.1.2"
blake2_c             = "0.2.0"
rand                 = "0.4"
smallvec             = "0.6"
nom                  = "3.2"
# time                 = "0.1"
chrono               = "0.4"
enum-map             = "0.2"
# threadpool           = "1.7"
# scoped_threadpool    = "0.1"
pond                 = "0.2"
futures              = "0.1"
clap                 = "2.30.0"
ctrlc                = "3.1.0"